project_name: import-tools
builds:
  - env:
      - CGO_ENABLED=0
    binary: import-tools
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -w
      - -s
    flags:
      - --trimpath
    main: main.go
dist: release
archives:
  - rlcp: true
    files:
      - LICENSE*
      - README*
      - start.sh
checksum:
  name_template: "checksums.txt"
