import { t } from 'i18next';

export default {
  importData: [
    { title: t('steps.loginONES') },
    { title: t('steps.selectBackup') },
    { title: t('steps.analyzeBackup') },
    { title: t('steps.selectONESTeam') },
    { title: t('steps.selectJiraProject') },
    { title: t('steps.issueMapping') },
    { title: t('steps.fieldMapping') },
    { title: t('steps.otherDataMapping') },
    { title: t('steps.userMapping') },
    { title: t('steps.viewConfig') },
    { title: t('steps.migrate') },
  ],
  importIndexData: [
    '/page/analyze/environment',
    '/page/analyze/pack',
    '/page/analyze/progress',
    '/page/analyze/team',
    '/page/analyze/import_project',
    '/page/analyze/issue_map',
    '/page/import_pack/init_password',
    '/page/analyze/result',
    '/page/import_pack/progress',
    '/page/import_pack/result',
  ],
  analyzeData: [
    { title: t('steps.loginONES') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
    { title: t('analyzeResult.current.version') },
  ],
};
