name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build web
        run: |
          make build-web

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build api
        run: |
          make build-linux

      - name: Package
        run: |
          make package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: import-tools.tar.gz

      - name: Build Docker Image
        run: |
          make build-image

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve Image Tag
        run: |
          echo "::set-output name=image_tag::${GITHUB_REF/refs\/tags\//}"

      - name: Push image
        run: |
          make push-image
          make push-image IMAGE_TAG=${image_tag}
