name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build web
        run: |
          make build-web

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build api
        run: |
          make build-linux

      - name: Package
        run: |
          make package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: import-tools.tar.gz
